; This file was auto-generated by drush make
core = 7.x

api = 2
projects[drupal][version] = "7.x"

; Modules
projects[advanced_help][version] = "1.0"

projects[ctools][version] = "1.0"

projects[calendar][version] = "3.0"

projects[date][version] = "2.3"

projects[entity][version] = "1.0-rc1"

projects[field_group][version] = "1.1"

projects[field_permissions][version] = "1.0-beta2"

projects[hierarchical_select][version] = "3.0-alpha5"

projects[mass_contact][version] = "1.0-alpha5"

projects[menu_token][version] = "1.0-beta1"

projects[references][version] = "2.0"

projects[og][version] = "1.3"

projects[panels][version] = "3.2"

projects[privatemsg][version] = "1.2"

projects[switchtheme][version] = "1.0"

projects[token][version] = "1.0-rc1"

projects[views][version] = "3.3"

projects[webform][version] = "3.17"

projects[workflow][version] = "1.0"

projects[wysiwyg][version] = "2.1"

; Themes
projects[adaptivetheme][version] = "2.2"

projects[zen][version] = "3.1"

; Modules
; Please fill the following out. Type may be one of get, git, bzr or svn,
; and url is the url of the download.
projects[mwsam-editablefields-6907779][download][type] = ""
projects[mwsam-editablefields-6907779][download][url] = ""
projects[mwsam-editablefields-6907779][type] = "module"

; Themes
; Please fill the following out. Type may be one of get, git, bzr or svn,
; and url is the url of the download.
projects[STARTERKIT][download][type] = ""
projects[STARTERKIT][download][url] = ""
projects[STARTERKIT][type] = "theme"

; Please fill the following out. Type may be one of get, git, bzr or svn,
; and url is the url of the download.
projects[openpw][download][type] = ""
projects[openpw][download][url] = ""
projects[openpw][type] = "theme"

